### ISSUE TITLE
缺少 head 文件

### ISSUE THREAD

**Issue by liuzhier** [wd22222222/sdlpal_edit#1]
项目中的 glad 目录下缺少了 glad.h，导致项目无法编译，话说文化人大佬退 Q 了？我感到很遗憾，无法与大佬直接取得联系......

**Comment by wd22222222** [comment]
下一个glad,&nbsp; 3.0以上 就行了opengl 如果不会下网上搜一下，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月20日(周六) 晚上11:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wd22222222/sdlpal_edit] 缺少 head 文件 (Issue #1)




 
项目中的 glad 目录下缺少了 glad.h，导致项目无法编译，话说文化人大佬退 Q 了？我感到很遗憾，无法与大佬直接取得联系......

**Comment by liuzhier** [comment]
emmm，opengl是没问题了，，，但其他的的地方又出问题了，，，建议将项目整理为sdlpal那种，整齐堆放起来~

**Comment by wd22222222** [comment]
你好，你说的问题，可能是64位系统和32位系统之间差别所至，64位和32位系统所使用的库不一样，我不知道你编译是在哪个环节出的问题，如果是报链接错误，一般是库不对，如果你的环境可以正确编辑sdlpal 而编译不了本系统，可以改用32位系统试一试。因为sdlpal缺省是用32位系统，如果编辑成功了但运行时出问题，请将sdl2.dll相应版本拷贝到执行文件目录中去，如果sdl2.dll版本不对，会出现0x000007错误。还有sdl2的版本也要 2.07之后的版本，早期的版本有的函数不支持。

**Comment by liuzhier** [comment]
当前编译会报各种语法错误，，，但是只有编译时才会报（几千个），没有glad和sdl2问题........
![1](https://github.com/wd22222222/sdlpal_edit/assets/83107010/89d3f58b-0920-427d-99f3-1798a4f6b972)

**Comment by liuzhier** [comment]
### **编译问题已解决，建议将项目整理成以下仓库的形式，以便于开发：**
_https://github.com/liuzhier/sdlpal_edit_expansion.git_
