### ISSUE TITLE
编译正常，运行后，从游戏资源中解包的文本数据，显示在列表界面时出现乱码：比如角色名、物品、法术名、对话文本等

### ISSUE THREAD

**Issue by javaClazz** [wd22222222/sdlpal_edit#2]
我编译正常运行后，无法得到无乱码的界面：比如，修改我方属性的table界面，队友名称，法术名称，以及敌方属性中名称等，多处中文均显示乱码。
![FH)_2D}R7V4{5BA_WHRTZJ8](https://github.com/wd22222222/sdlpal_edit/assets/11263430/1a199a24-4837-44e2-ab58-9350774a321f)

我查看了下，存档、.data等文件里面存的文本是GBK编码的；
请问，应如何解决该问题？

**Comment by wd22222222** [comment]
你提出的问题，可能出在对游戏文件的文字编码测试函数未能正确识别，请跟踪pal1.app（1267行） -PAL_IsBig5函数返回值上否正确。如不行，换个不同的游戏版本试一试。

**Comment by wd22222222** [comment]
已经针对代码识别环节可能出现的问题，进行了修改，在修改初始数据-》修改游戏设置第50项下增加了系统字符集选项，可以进行设置了。

**Comment by javaClazz** [comment]
@wd22222222  大佬，代码更新后问题未解决。

经过测试，我推测问题可能是因为，大佬使用的游戏资源中、mkf文件里面的文本是以UTF-8编码保存的。
而我使用的，却是以GBK编码保存的，所以就算我同步最新代码后编译，改动游戏设置选项，乱码问题依然存在。

我修改底层代码，将 PAL_TextToUTF8() 换成以 Unicode 编码保存的字符串后，所有文本在界面上即可正常显示。

以下即为上述提及的游戏资源，大佬可以下载后测试一下：
https://registry.npmmirror.com/evans-sdlpal-source/1.0.0/files/assets/pal-game.zip

测试环境：
    1. win10 22H2，语言设置如下
![image](https://github.com/wd22222222/sdlpal_edit/assets/11263430/c016f42b-8dc0-4c31-9e33-754c72e2391f)

    2. vs2022，项目源代码文件以 UTF-8 + BOM 编码保存；
    3. 解压上述游戏资源后，设置项目属性->调试->工作目录：zip解压指定目录；
    4. 其它设置未改动，同项目工程自带；

PS: github 不能即时沟通，仅对技术讨论友好，大佬可以加QQ好友不？可以把联系信息加在“关于”对话框中嘛。
